var cvs = document.getElementById("canvas");
var ctx = cvs.getContext("2d");
ctx.beginPath();
ctx.arc(100, 100, 60, Math.PI, 0, true);
ctx.fill();
;
var ctx = cvs.getContext("2d");
ctx.beginPath();
ctx.arc(100, 100, 60, Math.PI, 0, true);
ctx.fill();
